### ISSUE TITLE
Margins for the attached documents

### ISSUE THREAD

**Issue by ludovicrenevey** [antistatique/retraitespopulaires-styleguide#104]
The margin between the content and the links is too big. 

![image](https://cloud.githubusercontent.com/assets/12033929/26146115/51fa1414-3aef-11e7-8f45-9eb45b029a2f.png)

**Comment by tonifisler** [comment]
@ludovicrenevey 😭  you ask the client to report issues following precise guidelines but I have to guess everything from your reports? 😭 

```
Titre du problème :
Contenu ne s'affiche pas sur page hôpital

Description du problème :
Les contenus détails (textes) ne s'affichent pas.

Description du résultat souhaité :
Le texte devrait simplement s'afficher comme sur les versions précédentes.

Navigateur utilisé :
Chrome, autre ?

URL : 
www.www.ch/mapage
```

**Comment by tonifisler** [comment]
The behaviour is working as designed. The spacing is below the whole block of content (text + contact CTA). If you have more text, the spacing is smaller.

**Comment by tonifisler** [comment]
Closing, as we surely won't be changing this thing 🙃
