### ISSUE TITLE
Organic Lines - Height parameters

### ISSUE THREAD

**Issue by jminguely** [antistatique/retraitespopulaires-styleguide#75]
It would be awesome to have a way to set the height / max amplitude of the waves when initializing the component Organic Lines.

There is a use case needing a smaller component on the header: https://projects.invisionapp.com/share/J69L38S8Z#/screens/209555858

Here is a demo achieved with a `transform: scaleY` on the container, not so fancy.
<img width="1128" alt="capture d ecran 2016-12-13 a 12 22 29" src="https://cloud.githubusercontent.com/assets/2260030/21138579/01ca9e58-c12f-11e6-9a16-953d69afdb59.png">

I also observed that the line goes beyond the container.
<img width="1124" alt="capture d ecran 2016-12-13 a 12 21 38" src="https://cloud.githubusercontent.com/assets/2260030/21138597/0e77412e-c12f-11e6-8b0c-7b318ad1a2aa.png">
Maybe putting the three path in the same SVG tag could be a bit more efficient.

**Comment by WengerK** [comment]
If you know how to do that I would be glad to get some help :D
