### ISSUE TITLE
[Theme CIP] strong in body content shouldn't be displayed in color

### ISSUE THREAD

**Issue by gido** [antistatique/retraitespopulaires-styleguide#84]
(imported from discussion https://antistatique.slack.com/archives/C0PG69H6W/p1491303402376723)
In my point of view, strong shouldn't be in color but just in bold...
I'm pretty sure users will found it confusing and think that it could be a link:

<img width="973" alt="screen_shot_2017-04-04_at_12 53 01" src="https://cloud.githubusercontent.com/assets/101859/24654897/1649f544-193c-11e7-9f95-f8a2f0d475c0.png">

Need confirmation from UX and Design team.

**Comment by gido** [comment]
oh, and I really found text justify ugly. Don't you ?

**Comment by gido** [comment]
Code I'm talking about is possibly here: https://github.com/antistatique/retraitespopulaires-styleguide/blob/4d80ce1aafca65cef7bc32cebafb23235b1c9d66/assets/sass/_ckeditor.scss#L74

**Comment by tonifisler** [comment]
Fixed  in 983612accb37d34a9be2eb167ddd5c99702c785d
